import { integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const services = sqliteTable("services", {
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  description: text("description").notNull(),
  features: text("features", { mode: "json" }).$type<string[]>().notNull(),
  icon: text("icon").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

export const portfolioItems = sqliteTable("portfolio_items", {
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  client: text("client").notNull(),
  category: text("category").notNull(),
  description: text("description").notNull(),
  link: text("link"),
  results: text("results", { mode: "json" }).$type<string[]>().notNull(),
  technologies: text("technologies", { mode: "json" }).$type<string[]>().notNull(),
  image: text("image"),
  featured: integer("featured", { mode: "boolean" }).notNull().default(false),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

export const testimonials = sqliteTable("testimonials", {
  id: text("id").primaryKey(),
  content: text("content").notNull(),
  author: text("author").notNull(),
  role: text("role").notNull(),
  company: text("company").notNull(),
  rating: integer("rating").notNull().default(5),
  avatar: text("avatar"),
  country: text("country"),
  countryCode: text("country_code"),
  linkedin: text("linkedin"),
  projectType: text("project_type"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

export const teamMembers = sqliteTable("team_members", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  role: text("role").notNull(),
  department: text("department").notNull(),
  bio: text("bio").notNull(),
  expertise: text("expertise", { mode: "json" }).$type<string[]>().notNull(),
  image: text("image"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

export const blogPosts = sqliteTable("blog_posts", {
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  slug: text("slug").notNull().unique(),
  excerpt: text("excerpt").notNull(),
  content: text("content").notNull(),
  author: text("author").notNull(),
  category: text("category").notNull(),
  tags: text("tags", { mode: "json" }).$type<string[]>().notNull(),
  publishedAt: text("published_at").notNull(),
  readTime: integer("read_time").notNull().default(5),
  featured: integer("featured", { mode: "boolean" }).notNull().default(false),
  featuredImage: text("featured_image"),
  featuredImageAlt: text("featured_image_alt"),
  featuredImageTitle: text("featured_image_title"),
  featuredImageCaption: text("featured_image_caption"),
  seoTitle: text("seo_title"),
  metaDescription: text("meta_description"),
  focusKeyword: text("focus_keyword"),
  secondaryKeywords: text("secondary_keywords", { mode: "json" }).$type<string[]>().notNull().default([]),
  canonicalUrl: text("canonical_url"),
  robotsIndex: integer("robots_index", { mode: "boolean" }).notNull().default(true),
  robotsFollow: integer("robots_follow", { mode: "boolean" }).notNull().default(true),
  ogTitle: text("og_title"),
  ogDescription: text("og_description"),
  ogImage: text("og_image"),
  ogImageAlt: text("og_image_alt"),
  twitterTitle: text("twitter_title"),
  twitterDescription: text("twitter_description"),
  twitterImage: text("twitter_image"),
  faqs: text("faqs", { mode: "json" }).$type<{ question: string; answer: string }[]>().notNull().default([]),
  status: text("status").notNull().default("published"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  versionHistory: text("version_history", { mode: "json" }).$type<{ version: number; title: string; updatedAt: string; author: string; note?: string }[]>().notNull().default([]),
});

export const jobPositions = sqliteTable("job_positions", {
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  department: text("department").notNull(),
  location: text("location").notNull(),
  type: text("type").notNull(),
  experience: text("experience").notNull(),
  description: text("description").notNull(),
  responsibilities: text("responsibilities", { mode: "json" }).$type<string[]>().notNull(),
  requirements: text("requirements", { mode: "json" }).$type<string[]>().notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

export const siteContent = sqliteTable("site_content", {
  id: text("id").primaryKey(),
  key: text("key").notNull().unique(),
  value: text("value", { mode: "json" }).$type<unknown>().notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

export const businesses = sqliteTable("businesses", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  slug: text("slug").notNull().unique(),
  category: text("category").notNull(),
  city: text("city").notNull(),
  country: text("country").notNull(),
  shortDescription: text("short_description").notNull(),
  description: text("description").notNull(),
  rating: real("rating").notNull().default(4.5),
  reviewCount: integer("review_count").notNull().default(0),
  address: text("address"),
  phone: text("phone"),
  website: text("website"),
  hours: text("hours", { mode: "json" }).$type<{ day: string; hours: string }[]>().notNull(),
  tags: text("tags", { mode: "json" }).$type<string[]>().notNull(),
  image: text("image"),
  featured: integer("featured", { mode: "boolean" }).notNull().default(false),
  isRemote: integer("is_remote", { mode: "boolean" }).notNull().default(false),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

export const pages = sqliteTable("pages", {
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  slug: text("slug").notNull().unique(),
  excerpt: text("excerpt").notNull().default(""),
  content: text("content").notNull().default(""),
  pageType: text("page_type").notNull().default("standard"),
  featuredImage: text("featured_image"),
  featuredImageAlt: text("featured_image_alt"),
  featuredImageTitle: text("featured_image_title"),
  featuredImageCaption: text("featured_image_caption"),
  seoTitle: text("seo_title"),
  metaDescription: text("meta_description"),
  focusKeyword: text("focus_keyword"),
  secondaryKeywords: text("secondary_keywords", { mode: "json" }).$type<string[]>().notNull().default([]),
  canonicalUrl: text("canonical_url"),
  robotsIndex: integer("robots_index", { mode: "boolean" }).notNull().default(true),
  robotsFollow: integer("robots_follow", { mode: "boolean" }).notNull().default(true),
  includeInSitemap: integer("include_in_sitemap", { mode: "boolean" }).notNull().default(true),
  sitemapPriority: real("sitemap_priority").notNull().default(0.8),
  changeFrequency: text("change_frequency").notNull().default("monthly"),
  ogTitle: text("og_title"),
  ogDescription: text("og_description"),
  ogImage: text("og_image"),
  ogImageAlt: text("og_image_alt"),
  twitterTitle: text("twitter_title"),
  twitterDescription: text("twitter_description"),
  twitterImage: text("twitter_image"),
  schemaType: text("schema_type").notNull().default("WebPage"),
  faqs: text("faqs", { mode: "json" }).$type<{ question: string; answer: string }[]>().notNull().default([]),
  status: text("status").notNull().default("draft"),
  author: text("author").notNull().default("Glovax Team"),
  featured: integer("featured", { mode: "boolean" }).notNull().default(false),
  readTime: integer("read_time").notNull().default(3),
  scheduledAt: integer("scheduled_at", { mode: "timestamp" }),
  publishedAt: integer("published_at", { mode: "timestamp" }),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  versionHistory: text("version_history", { mode: "json" }).$type<{ version: number; title: string; updatedAt: string; author: string; note?: string }[]>().notNull().default([]),
});

export const redirects = sqliteTable("redirects", {
  id: text("id").primaryKey(),
  source: text("source").notNull().unique(),
  destination: text("destination").notNull(),
  statusCode: integer("status_code").notNull().default(301),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});
